version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    target-branch: main